# This will host the environment information for the docker container
# It will also define the identity of the containe 
# It will also define the python requuirements 
# Importing the lanenet evaluation code to the container

FROM python:3.10.20-slim

LABEL maintainer="suyog224356@gmail.com"
LABEL description="Docker container for lane detection using Ultra Fast Lane Detection"
LABEL python_version="3.10.20"

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

    
RUN git clone https://github.com/cfzd/Ultra-Fast-Lane-Detection.git ufld
    
WORKDIR /app/ufld

COPY . .

CMD ["python", "server.py"]